#!/usr/bin/env python3
"""Generate manuscript macros from the canonical IGM transmission result."""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import os
import tempfile
from pathlib import Path
from typing import Any


def _number(record: dict[str, Any], field: str, source: Path) -> float:
    current: Any = record
    for part in field.split("."):
        if not isinstance(current, dict) or part not in current:
            raise ValueError(f"{source}: missing numeric field {field}")
        current = current[part]
    if isinstance(current, bool) or not isinstance(current, (int, float)):
        raise ValueError(f"{source}: field {field} is not numeric")
    value = float(current)
    if not math.isfinite(value):
        raise ValueError(f"{source}: field {field} is not finite")
    return value


def _scientific(value: float, significant_digits: int = 3) -> str:
    exponent = math.floor(math.log10(abs(value)))
    coefficient = value / 10.0**exponent
    decimals = significant_digits - 1
    return f"{coefficient:.{decimals}f}\\times10^{{{exponent}}}"


def render_macros(source: Path) -> str:
    record = json.loads(source.read_text(encoding="utf-8"))
    if record.get("schema_version") != 1:
        raise ValueError("unsupported IGM transmission schema version")
    wavelength_difference_points = 100.0 * (
        _number(record, "derived.nominal_transmission", source)
        - _number(record, "derived.gray_transmission", source)
    )
    macros = {
        "IgmDensityKernelIntegral": (
            f"{_number(record, 'integrals.density_kernel', source):.3f}"
        ),
        "IgmDustKernelIntegral": (
            f"{_number(record, 'integrals.dust_kernel', source):.3f}"
        ),
        "IgmEffectiveDensityPathGpc": (
            f"{_number(record, 'integrals.effective_density_path_gpc', source):.2f}"
        ),
        "IgmVisualDustOpacity": _scientific(
            _number(record, "derived.dust_visual_opacity_gpc_inverse", source)
        ),
        "IgmLaunchToVisualExtinctionRatio": (
            f"{_number(record, 'derived.dust_launch_to_visual_ratio', source):.3f}"
        ),
        "IgmDustOpacity": _scientific(
            _number(record, "derived.dust_opacity_gpc_inverse", source)
        ),
        "IgmDustOpticalDepth": _scientific(
            _number(record, "derived.dust_optical_depth", source)
        ),
        "IgmDustTransmission": (
            f"{_number(record, 'derived.dust_transmission', source):.4f}"
        ),
        "IgmElectronOpticalDepth": _scientific(
            _number(record, "derived.electron_optical_depth", source)
        ),
        "IgmElectronTransmission": (
            f"{_number(record, 'derived.electron_transmission', source):.4f}"
        ),
        "IgmGalaxyOpticalDepth": _scientific(
            _number(record, "derived.galaxy_optical_depth", source)
        ),
        "IgmGalaxyTransmission": (
            f"{_number(record, 'derived.galaxy_transmission', source):.4f}"
        ),
        "IgmNominalOpticalDepth": _scientific(
            _number(record, "derived.nominal_optical_depth", source)
        ),
        "IgmNominalTransmission": (
            f"{_number(record, 'derived.nominal_transmission', source):.4f}"
        ),
        "IgmGrayDustOpticalDepth": _scientific(
            _number(record, "derived.gray_dust_optical_depth", source)
        ),
        "IgmGrayTotalOpticalDepth": _scientific(
            _number(record, "derived.gray_total_optical_depth", source)
        ),
        "IgmGrayTransmission": (
            f"{_number(record, 'derived.gray_transmission', source):.4f}"
        ),
        "IgmWavelengthDependenceTransmissionDifferencePoints": (
            f"{wavelength_difference_points:.2f}"
        ),
    }
    digest = hashlib.sha256(source.read_bytes()).hexdigest()
    lines = [
        "% Generated by analysis/generate_igm_values.py; do not edit.",
        f"% Source SHA-256: {digest}",
    ]
    lines.extend(
        rf"\newcommand{{\{name}}}{{{value}}}" for name, value in macros.items()
    )
    return "\n".join(lines) + "\n"


def write_atomically(output: Path, content: str) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        prefix=f".{output.name}.", dir=output.parent
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8") as handle:
            handle.write(content)
        temporary.replace(output)
    except BaseException:
        temporary.unlink(missing_ok=True)
        raise


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    write_atomically(args.output, render_macros(args.source))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
